// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storage.Data;

#nullable disable

namespace Storage.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20221220144815_ChangeProduct")]
    partial class ChangeProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Storage.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            Count = 0,
                            Description = "",
                            Name = "Titanic",
                            OrderDate = new DateTime(1997, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10,
                            Shelf = "2.0F"
                        },
                        new
                        {
                            Id = 2,
                            Category = 7,
                            Count = 0,
                            Description = "",
                            Name = "Screem",
                            OrderDate = new DateTime(2005, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10,
                            Shelf = "2.0F"
                        },
                        new
                        {
                            Id = 3,
                            Category = 6,
                            Count = 0,
                            Description = "",
                            Name = "The Shining",
                            OrderDate = new DateTime(1997, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10,
                            Shelf = "2.0F"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Count = 0,
                            Description = "",
                            Name = "300",
                            OrderDate = new DateTime(2000, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10,
                            Shelf = "2.0F"
                        },
                        new
                        {
                            Id = 5,
                            Category = 32,
                            Count = 0,
                            Description = "",
                            Name = "Interstellar",
                            OrderDate = new DateTime(2014, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10,
                            Shelf = "2.0F"
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            Count = 0,
                            Description = "",
                            Name = "The Dark Knight",
                            OrderDate = new DateTime(2008, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10,
                            Shelf = "2.0F"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
